### ISSUE TITLE
Effects are not typed with TypeScript

### ISSUE THREAD

**Issue by HeyMarcy** [cloudinary-community/next-cloudinary#214]
Regarding the note "All effect props are disabled by default", how does one enable them?
I don't seem to be able to use the border effect.

**Comment by colbyfayock** [comment]
hey @HeyMarcy the word "disabled" probably wasn't the best choice of word - what that means is that all of the effects default to nothing, they're not turned on. I'll make a change to the documentation to make that more clear

all effects props should work as shown either in the configuration page or on the examples page

as far as border goes, you can see an example here:

https://next-cloudinary.spacejelly.dev/components/cldimage/examples#border

```
<CldImage
  ...
  border="40px_solid_purple"
/>
```

If that's not working, can you share your code snippet and the resulting image URL?

**Comment by colbyfayock** [comment]
also of note - this is the documentation for how the border property currently works, it uses the standard Cloudinary transformation API: https://cloudinary.com/documentation/transformation_reference#bo_border

though my hope is to eventually make it more intuitive for the prop option

**Comment by HeyMarcy** [comment]
I was able to 'cheat' and add a border prop to ImageOptions. I got the border locally, but the build failed.

**Comment by HeyMarcy** [comment]
I was able to get the borders to work using the transformation API:
```
 <Image
  ...
  src={`https://res.cloudinary.com/${process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}/image/upload/c_thumb,g_faces,h_140,w_200/bo_10px_solid_black/${public_id}.${format}`}
/>
```

**Comment by colbyfayock** [comment]
i pushed a change for the effects props but now im seeing a bigger issue with the border typescript error that somehow i overlooked and didnt come up yet, that it seems a lot of effect props are missing types

will be trying to figure out a solution for that as it's currently not simple to "just add". thanks for bringing this up

**Comment by danieltott** [comment]
I would love to take a crack at this if it's still available!

**Comment by colbyfayock** [comment]
hey @danieltott - this ticket is somewhat tied to work that needs to be done through the dependency that creates the URLs: https://github.com/colbyfayock/cloudinary-util/issues/53

However - because I've been slow to get that done because of other priorities, I wouldn't be opposed to adding those types here in the meantime, to make them available and improve the DX until the core work is completed.

I'll assign it to you, but I encourage giving it a quick look and seeing what you think in that regard

**Comment by danieltott** [comment]
@colbyfayock would it make sense for me to do the work there? It seems like it'd be better to have a single source of truth for that sort of thing

**Comment by colbyfayock** [comment]
my only concern is i think its a bit of a can of worms. i fully support and would love to see you contribute there, but let me lay it out quick so you're aware

the way that cloudinary Util works is I export a function that creates URLs. this is whats used in Next Cloudinary

through that I have a plugin system that allows us to create small chunks of transformation code to perform different actions

https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/lib/cloudinary.ts#L86

this is where the problem lays as the effects are tied to this plugin system and it just makes it trickier to work with the types

example: https://github.com/colbyfayock/cloudinary-util/blob/main/packages/url-loader/src/plugins/effects.ts

i've started some work that is somewhat, but not totally related, converting some of the project to zod, but i can easily scrape that or rework it with new underlaying changes as ive been slow with it, learning while i've been working

https://github.com/colbyfayock/cloudinary-util/pull/52

with all of this said, if that feels comfortable for ryou to tackle, i'd be thrilled for you to help out with any part of the above, including figuring out a path forward and starting with the types, or you can add the types here for now :)

what do you think?

**Comment by colbyfayock** [comment]
hahaha sounds great. looking forward to seeing what you come up with! (maybe 😄)

**Comment by colbyfayock** [comment]
this should now be resolved!!

<img width="1073" alt="image" src="https://github.com/cloudinary-community/next-cloudinary/assets/1045274/0222c95b-4565-4285-bb4e-bcbbb779511b">

https://github.com/cloudinary-community/next-cloudinary/issues/363
https://github.com/colbyfayock/cloudinary-util/pull/143
