### ISSUE TITLE
Bundle size indication in docs

### ISSUE THREAD

**Issue by aldendaniels** [cloudinary-community/next-cloudinary#218]
Hi @colbyfayock, thanks for your thoughtful work on this integration. Overall this looks like a far better solution for using Cloudinary in NextJS then anything else I've seen. 

It'd be helpful to have a sense of what the weight of this is (minified, unminified, etc), especially as this takes a dependency on some Cloudinary libs that also don't specify bundle weight.

I'm planning to do a bit of testing and report back, happy to share results if you don't know offhand. One way or another it'd be a nice touch to add this to the docs.

**Comment by colbyfayock** [comment]
thanks @aldendaniels!

i think thats a great idea. do you have any examples of how youve seen this shown in a helpful way in other projects?

woudl love to hear what you find out and you're welcome to plug in a PR if you'd like

**Comment by aldendaniels** [comment]
Sure! Here's an example from the lib: https://www.npmjs.com/package/libphonenumber-js

<img width="728" alt="Screenshot 2023-06-21 at 1 09 23 PM" src="https://github.com/colbyfayock/next-cloudinary/assets/4658558/7f96f3d3-5ae9-466e-8268-30ce5eaa34de">

**Comment by JPVRS** [comment]
Any update on this? I was just wondering this myself, and stumbled across this posted issue. Specifically wondering about the impact on the JS payload compared to just passing a custom loader to the Next.js Image component (obviously the latter wouldn't have the same ease of using transformations.)

**Comment by colbyfayock** [comment]
hey jumping back to this - i found that i can have this dynamically added with shields.io and bundlephobia

![npm bundle size](https://img.shields.io/bundlephobia/min/next-cloudinary?style=flat-square&label=Minified%20Size)

going to add this to the readme

**Comment by colbyfayock** [comment]
<img width="715" alt="image" src="https://github.com/cloudinary-community/next-cloudinary/assets/1045274/efabc1a7-c4b4-4691-b408-14b5f5841d26">

the thing to keep in mind is unless there's an underlaying or im mistaken, in reality, that size won't be added to the bundle through after treeshaking, so if you're just using the CldImage, it wont impact it to the extent shown there
