### ISSUE TITLE
CldImage with unoptimized flag renders image with wrong url

### ISSUE THREAD

**Issue by pschaub** [cloudinary-community/next-cloudinary#245]
I am trying to use `next-cloudinary` in my Next.js project:
```ts
"use client";

import {CldImage} from "next-cloudinary";

export default function ExampleComponent() {
    return (
            <CldImage
                width="100"
                height="100"
                src="testimage"
            />
    );
}
```

I added `NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=` (+ cloud name at the end) to my `.env` file.
I am running locally in dev mode (`npm run dev`).

The rendered image is shown like this:
```html
<img loading="lazy" width="100" height="100" decoding="async" data-nimg="1" style="" src="http://localhost:3000/testimage">
```

Why is the URL of the image not automatically generated to use Cloudinary?

**Comment by pschaub** [comment]
I've identified the issue:

If you've globally enabled the `unoptimized` flag ([link to the documentation](https://nextjs.org/docs/pages/api-reference/components/image#unoptimized)) in your `next.config.js` file, the Cloudinary URL will not be generated. 

I've disabled this to [minimize Image Optimization costs](https://vercel.com/docs/concepts/image-optimization/managing-image-optimization-costs#how-to-minimize-image-optimization-costs).

I have a couple of questions and suggestions:

- Do I understand correctly, that enabling this optimization while just using `CldImage` will **NOT** trigger any image optimization costs on Vercel?

- If this is correct, I'd like to suggest the following:
   - The `CldImage` component should set the `unoptimized` flag to `false` by default. This would ensure that the `CldImage` component works as expected out of the box, even with a globally enabled `unoptimized` flag.

**Comment by colbyfayock** [comment]
@pschaub i haven't seen this one before, thanks for flagging it!

as far as the `unoptimized` flag, it looks like it things its a local file, so the localhost/file is trying to reference that, which is not accurate.

The CldImage component delivers a Cloudinary URL via the Loader pattern: https://nextjs.org/docs/pages/api-reference/components/image#loader

My understanding is this completely bypasses anything that Vercel would do, unless somehow they're doing something when deployed? But it's ultimately giving you a Cloudinary URL, so I'm not sure what the effect would be there. I'd love to hear if you have a different understanding or have seen something different.

i'm kind of surprised that this impacts the component as I would expect the loader to still be used to transform the image, where clearly it's not. so perhaps what i need to do is recognize the unoptimized flag and transform the `src` that gets passed into the Image component in that case

would you like to explore this in a PR? otherwise I can try to get to this sometime soon. i would just like to understand the impact first of that flag and the loader solution

**Comment by pschaub** [comment]
@colbyfayock I believe I may have found some relevant information that might clarify the situation regarding the `unoptimized` prop and its interaction with a custom loader function.

According to the issue https://github.com/vercel/next.js/issues/50764, it appears that the `unoptimized` prop and the `loader` prop can't be used together.

I'm not entirely certain if disabling `unoptimized` would result in Vercel performing some optimizations that could incur additional costs. Given the financial implications, I believe it's essential to have a clear understanding of this interaction before implementing any changes.

I would greatly appreciate if anyone could provide further insights on whether using CldImage with the unoptimized flag disabled would trigger any extra optimizations on Vercel's end, and if so, whether these would come with any cost implications. This information would allow us to ensure that we're offering the best and most cost-effective solution for CldImage usage.

**Comment by vader1359** [comment]
@pschaub I remove the global `unoptimized:true` in next.config.js then fetch some images using the `<CldImage>` and `next/image` Image component at the same time.
This is the `<CldImage`:
```<img alt="text" loading="lazy" width="500" height="500" decoding="async" data-nimg="1" class="Packshot-sc-c9707e0a-0 yNoLj" style="color:transparent" srcset="https://res.cloudinary.com/iant1359/image/upload/c_limit,w_500/e_grayscale/f_auto/q_auto/v1690518705/nanohome/website/others/lrkel3iiu4cvs725thpq?_a=BAVAXgGd0 1x, https://res.cloudinary.com/iant1359/image/upload/c_limit,w_500/e_grayscale/f_auto/q_auto/v1690518705/nanohome/website/others/lrkel3iiu4cvs725thpq?_a=BAVAXgGd0 2x" src="https://res.cloudinary.com/iant1359/image/upload/c_limit,w_500/e_grayscale/f_auto/q_auto/v1690518705/nanohome/website/others/lrkel3iiu4cvs725thpq?_a=BAVAXgGd0">```

And this is the `next/image` component:
```<img loading="lazy" width="200" height="300" decoding="async" data-nimg="1" style="color:transparent" srcset="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fiant1359%2Fimage%2Fupload%2Fnanohome%2Fremote_media_website%2F1af0c1a531394eac6b4ba5b79f83719f%2F90647195%2Fwhite-background-image-of-fritz-hansen-swan-3320-lounge-fully-upholstered-walnut-grace-leather-brushed-aluminum-base-recqzobns48epntpu.jpg&amp;w=256&amp;q=75 1x, /_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fiant1359%2Fimage%2Fupload%2Fnanohome%2Fremote_media_website%2F1af0c1a531394eac6b4ba5b79f83719f%2F90647195%2Fwhite-background-image-of-fritz-hansen-swan-3320-lounge-fully-upholstered-walnut-grace-leather-brushed-aluminum-base-recqzobns48epntpu.jpg&amp;w=640&amp;q=75 2x" src="/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fiant1359%2Fimage%2Fupload%2Fnanohome%2Fremote_media_website%2F1af0c1a531394eac6b4ba5b79f83719f%2F90647195%2Fwhite-background-image-of-fritz-hansen-swan-3320-lounge-fully-upholstered-walnut-grace-leather-brushed-aluminum-base-recqzobns48epntpu.jpg&amp;w=640&amp;q=75">```

So all the images optimized by `next/image` has the src like `/_next/image...` and the `<CldImage>` has Cloudinary url, so I think It's same to assume that only the next/image will trigger the source image count in billing.

If you wanna make sure, you can have a look on Vercel usage. This list down the image source optimized by vercel.
![CleanShot 2023-07-30 at 23 41 58](https://github.com/colbyfayock/next-cloudinary/assets/27997820/1c68fad3-f7f1-4f7c-82b1-81c5b9049a0e)

**Comment by colbyfayock** [comment]
that make sense. the docs are hosted on vercel and don't have a single instance of usage 

<img width="896" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/cec93b56-4d24-4738-8aaa-e3b7d289d7e7">

**Comment by colbyfayock** [comment]
as far as what to do to address this, it looks like to resolve this, i can update the `src` to use a fully constructed Cloudinary URL and it works, where normally we would need and `image` configuration for an allowed list, it seems that with `unoptimized` it bypasses that

additionally, what it can do is disable the `f_auto` and `q_auto` from occurring on the Cloudinary URL, which will deliver it "unoptimized"

the thing im only unsure of now is how this works with the globally configurable unoptimized flag. the only thing i cna think of is once `getImgProps` is available  i might be able to use that, but it would only work from that version forward

https://twitter.com/leeerob/status/1674250190432116736

for now this PR addresess the prop, but i would imagine the globally setting is the more common use case:

https://github.com/colbyfayock/next-cloudinary/pull/250

thoughts on the global option? i can't seem to figure out a way to access the value from within the library component

**Comment by colbyfayock** [comment]
good news, found out from Vercel that the flag is available to inspect through `process.env.__NEXT_IMAGE_OPTS` 

Fixed in: https://github.com/colbyfayock/next-cloudinary/pull/253
