### ISSUE TITLE
[Bug] GitHub Action workflow does not fail when release doesn't occur

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#292]
# **Bug Report**

## **Describe the bug**

This workflow didn't produce a release: https://github.com/colbyfayock/next-cloudinary/actions/runs/6385327098/job/17329871389

It should have given it was a fix, however it looks like the local branch was behind remote for some reason, but if this happens, the action should have failed to notify the project it needs to be addressed

**Comment by Vaibhav91one** [comment]
Would like to work on this?

**Comment by colbyfayock** [comment]
hey @Vaibhav91one as mentioned on the other Issue, let's work on 1 issue at a time, so we can give someone else the opportunity to work on this while you work on the other. but if the other is merged and no one else has claimed this issue, id be happy to assign it to you!

**Comment by Vaibhav91one** [comment]
> hey @Vaibhav91one as mentioned on the other Issue, let's work on 1 issue at a time, so we can give someone else the opportunity to work on this while you work on the other. but if the other is merged and no one else has claimed this issue, id be happy to assign it to you!

Sure.

**Comment by YonatanKra** [comment]
Hi @colbyfayock 
I can take this one.
Seems like there's a `semantic-release` action. Would it make sense if I used it?

**Comment by colbyfayock** [comment]
@YonatanKra definitely not opposed to using that if it fixed everything and still works similarly to before! assigning it over

**Comment by colbyfayock** [comment]
hey @YonatanKra are you still working on this?

**Comment by colbyfayock** [comment]
Unassigning to make available for others
