### ISSUE TITLE
[Bug] Signed Request is `text/plain;charset=UTF-8` instead of `application/json`

### ISSUE THREAD

**Issue by vschoener** [cloudinary-community/next-cloudinary#379]
# **Bug Report**

## **Describe the bug**

When using the `CldUploadWidget` widget to sign the URL, it seems that the request it sents is not `application/json`. Is it possible to change this behavior?

FastAPI backend is returning a 422 response in the case it's a `text/plain;charset=UTF-8` and ideally would be nice to use `json`

Of course, with a nodejs server; it doesn't really care about the type and transform the data into an object, but with python and Fastapi server, it's slightly different.

## **Is this a regression?**

Nop

## **Steps To Reproduce the error**

Create a fast API backend server with a route that takes a `BaseModel` to transform the payload into an object and request the route

## **Expected behaviour**

I expect the request being a content-type application/json, here is the 422 response

```json
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.4/v/missing"
        }
    ]
}

```
### **Your environment**

- OS: Mac
- Node version: 21.1
- Npm version: 10.2.0
- Browser name and version: Chrome and Postman

**Comment by vschoener** [comment]
I just found that I can send a `Request` object instead of the `SignedURL` so I tried this code and it worked :) 

``` json
    const headers = new Headers();
    headers.append("Content-Type", "application/json");

    const options = {
        method: "GET",
        headers: headers,
        mode: "cors",
        cache: "default",
    };


    const request = new Request("http://localhost:8000/cloudinary/signedURL", options)
```

**Comment by colbyfayock** [comment]
oh interesting! glad that worked. but sounds like i can add those headers to the baked in fetch request to solve that for you

https://github.com/colbyfayock/next-cloudinary/blob/main/next-cloudinary/src/components/CldUploadWidget/CldUploadWidget.tsx#L148

i'll get that added!

**Comment by colbyfayock** [comment]
going to hold this for a potential inclusion in [v6.0.0](https://github.com/colbyfayock/next-cloudinary/issues/363) as i belive this would be a breaking change
```
      headers: {
        'Content-Type': 'application/json'
      }
```
once i add that to the fetch request, the `req.body` in the API route (Pages Router) breaks as it stands in the docs because i'm parsing the body. passing that content-type is the right move but want to avoid that sort of change going in a minor to prevent it occurring in other's applications unexpectedly
