### ISSUE TITLE
[Bug] Colors prop not working

### ISSUE THREAD

**Issue by PhilipAngelinNE** [cloudinary-community/next-cloudinary#386]
# **Bug Report**

## **Describe the bug**

I have tried putting both e.g "red" and hex format colors on the `base`, `text` and `accent` color properties, but they don't seem to do anything as the player remains visually the same.

## **Is this a regression?**

Haven ever tried this player, or prop, before so can't tell.

## **Steps To Reproduce the error**

1. Example use of the colors prop: `colors={{ base: '#FF0000', text: 'green', accent: 'rgb(255, 255, 0)' }}`

## **Expected behaviour**

I expect som colors to change, not sure which though, that's what I wanted to try out.

### **Your environment**

- OS: Windows 11 | 23H2
- Node version: 20.10.0
- Npm version: 10.2.3
- Browser name and version: Chrome 120.0.6099.71

**Comment by colbyfayock** [comment]
hey @PhilipAngelinNE do you happen to have multiple video instances on the page? if so, can you try specifiying an ID for each of them?

i seem to be able to make it work on my end pasting the prop

```
<CldVideoPlayer
  id="basic"
  width="1620"
  height="1080"
  src={`${process.env.VIDEOS_DIRECTORY}/mountain-stars`}
  colors={{ base: '#FF0000', text: 'green', accent: 'rgb(255, 255, 0)' }}
/>
```

<img width="1294" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/1c3ec843-c11e-401b-bc89-ac295b78c936">

one challenge with the API is that using multiple instances without an ID can create conflicts in the initialization with custom settings like that between the different players, so setting a unique ID for each can solve that

**Comment by colbyfayock** [comment]
strange - it should set an ID by default if not added:

```
const playerId = id || `player-${publicId.replace('/', '-')}`;
```

the issue typically arrises if multiple instances are causing the issue because there's not a solid mechanism to create unique IDs that dont mismatch between the server and client
