### ISSUE TITLE
Feedback for “Error: I don't know why in CldImage I am getting Type Error. Using Next 14."

### ISSUE THREAD

**Issue by SyedMustafaqadri** [cloudinary-community/next-cloudinary#402]
Error:
[Type '{ width: "600"; height: "400"; src: string; tint: string; sizes: string; alt: string; }' is not assignable to type 'IntrinsicAttributes & Omit<ImageProps, "src"> & ImageOptions & { config?: ConfigOptions | undefined; preserveTransformations?: boolean | undefined; src: string; unoptimized?: boolean | undefined; } & RefAttributes<...>'.
  Property 'tint' does not exist on type 'IntrinsicAttributes & Omit<ImageProps, "src"> & ImageOptions & { config?: ConfigOptions | undefined; preserveTransformations?: boolean | undefined; src: string; unoptimized?: boolean | undefined; } & RefAttributes<...>'.]

**Comment by colbyfayock** [comment]
@SyedMustafaqadri can you share your code?

**Comment by colbyfayock** [comment]
closing without addtional context
