### ISSUE TITLE
Analytics throws request error 

### ISSUE THREAD

**Issue by coderdix24** [cloudinary-community/next-cloudinary#403]
# **Bug Report**

## **Describe the bug**
Getting the following error with analytics or cloundinaryAnalytics props are set to true. I'm assuming it has to do with some CORs issue. 
POST https://video-analytics-api.cloudinary.com/v1/video-analytics net::ERR_BLOCKED_BY_CLIENT

## **Is this a regression?**

Not sure

## **Steps To Reproduce the error**

1. Use the CldVideoPlayer component 
2. set analytics or cloudinaryAnalytics prop value to true

## **Expected behaviour**

I could see this being a next js thing. Wasn't sure what I was expecting, as I'd imagine some configuration needs to change somewhere but wanted to see what the official word was on handling this. I'm trying to get the videos into the analytics section of my cloudinary dashboard.

### **Your environment**

- OS:  Mac OS
- Node version: v18.17.1
- Npm version: 9.6.7
- Browser name and version: Brave v120

## **Additional context**

cloudinaryAnalytics property complains and isn't in the package's documentation but is in cloudinary's.

**Comment by colbyfayock** [comment]
hey @coderdix24 as far as i know analytics should work out of the box

This is what it looks like for me when accessing the Analytics page within the console without any custom configuration from this library's documentation pages

<img width="1604" alt="image" src="https://github.com/cloudinary-community/next-cloudinary/assets/1045274/cb39e2de-4e41-4e73-b7ce-63b6a3dff6d1">

see the top of this page for a bit more info: https://cloudinary.com/documentation/video_analytics

are you not seeing anything in your analytics tab with the default player configuration? If not, can you share with me your code or even better, if you have the player publicly available somewhere?

That said, I think i need to add support for custom analytics, but it sounds like you just want analytics to be generally turned on with Cloudinary's default configuration, is that correct? Which again, should work by default.

**Comment by colbyfayock** [comment]
closing, but please follow up if you have additional info!
