### ISSUE TITLE
[Feature] Can we add support for custom domain?

### ISSUE THREAD

**Issue by 0xdhrv** [cloudinary-community/next-cloudinary#404]
# Add support for custom domain

## We can use Cloudinary with a custom domain, so if this could support this?

We have a Cloudinary custom domain, and we would like to use the same with this image component and utils. Both of these should work, given we pass the correct domain for the same. (https://cloudinary.com/documentation/advanced_url_delivery_options#private_cdns_and_cnames)

```txt
res.cloudinary.com/<cloudname>/<...asset info>

custom.domain.com/<...asset info>
```

## **Describe the solution you'd like**

A prop extension on config to support custom domain.

## **Describe alternatives you've considered**

None, I am planning on using the `getCldImageUrl` response and replacing the same with a custom domain to get the desired results.

**Comment by colbyfayock** [comment]
hey @0xdhrv that function should actually support a custom config like that! the second argument allows you to pass in the config object:

https://next.cloudinary.dev/getcldimageurl/configuration

```
getCldImageUrl(options, config)
```

For instance using an example image from my docs with a non-working cname:

```
getCldImageUrl({
    width: 960,
    height: 600,
    src: `images/turtle`
  }, {
    url: {
      secureDistribution: 'spacejelly.dev',
      privateCdn: true
    }
  })
```

gives me

```
https://spacejelly.dev/image/upload/c_limit,w_960/f_auto/q_auto/v1/images/turtle?_a=BAVAcNAO0
```

☝️ this isn't a real cname, just an example

want to give that a try?

**Comment by 0xdhrv** [comment]
Thanks, I belbelieve <CldImage /> would also support such

**Comment by 0xdhrv** [comment]
Thanks @colbyfayock, I believe `<CldImage />` would also support such options. or do we need to make some changes for the same?

**Comment by 0xdhrv** [comment]
Thanks this is already supported, I didn't find quicking in documentation review

**Comment by colbyfayock** [comment]
awesome! i'll try to get a page in there under Guides to help make it easier to find.

**Comment by 0xdhrv** [comment]
Yeah, I can update the docs for such, this is very helpful!
