### ISSUE TITLE
[Feature] Guide - Custom Domains

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#405]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add a new guide explaining how to set up custom domains.

**Comment by sragneau** [comment]
I dit it with config props: 
![image](https://github.com/cloudinary-community/next-cloudinary/assets/17569666/500ba6e1-6576-4e64-b357-920c3a3f24db)

**Comment by colbyfayock** [comment]
awesome glad that worked! i'll add a guide under here showing how to do that for others to more easily find

<img width="546" alt="image" src="https://github.com/cloudinary-community/next-cloudinary/assets/1045274/92f75954-ab01-41f4-b1d5-ec5e2f3e5089">

**Comment by Prathamesh010** [comment]
Assign me this issue. @colbyfayock

**Comment by colbyfayock** [comment]
done
