### ISSUE TITLE
[Bug] @ts-ignore in CldVideoPlayer.tsx

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#426]
# **Bug Report**

## **Describe the bug**

A @ts-ignore is currently in place in the CldVideoPlayer component which is utilizing a videojs method to dispose of the player

https://github.com/cloudinary-community/next-cloudinary/blob/main/next-cloudinary/src/components/CldVideoPlayer/CldVideoPlayer.tsx#L227-L228

Goal would be to address whatever type issues are preventing this line from being removed.

There is a dispose method on the player itself but it was causing issues apparently. so the answer may be adding the type somewhere, which now exist inside of https://github.com/colbyfayock/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.d.ts

some context: https://github.com/cloudinary-community/next-cloudinary/pull/317#issuecomment-1779905842

**Comment by colbyfayock** [comment]
update: this should now be available via a top level prop, confirm this is working wiht `playerRef.current?.dispose()` or generally address the issue

**Comment by Yash-sudo-web** [comment]
Hey @colbyfayock , i'd like to give this issue a try

**Comment by colbyfayock** [comment]
all yours! let me know if you have any questions

**Comment by Yash-sudo-web** [comment]
can you give some context on the issue? what exactly is the problem here, since on remove the ts-ignore no errors are being thrown by typescript

**Comment by Yash-sudo-web** [comment]
@colbyfayock , updating the type would mean i have to update CloudinaryVideoPlayer inside of '@cloudinary-util/types' which is an external dependency, how to proceed with this?

**Comment by Yash-sudo-web** [comment]
![Screenshot_20241003_231409](https://github.com/user-attachments/assets/18161729-e32c-4de1-8e03-b7c9f106930f)
i have added this videojs object by going into the node modules and the error seems to have disappeared now, but i don' know the source as to where do i push this code? probably some other repository

**Comment by colbyfayock** [comment]
@Yash-sudo-web you're welcome to make the change inside of that repository!

https://github.com/cloudinary-community/cloudinary-util/blob/main/packages/types/src/types/cloudinary-video-player.ts

**Comment by Yash-sudo-web** [comment]
https://github.com/cloudinary-community/next-cloudinary/pull/535
this is the PR to remove ts-ignore
