### ISSUE TITLE
[Bug] video would not play despite public ID given

### ISSUE THREAD

**Issue by monstajoe2002** [cloudinary-community/next-cloudinary#427]
# **Bug Report**

## **Describe the bug**
Currently, I have a convex database and I saved the public ID of the video in the database without issue. Now, when it's time to fetch that video with the other autogenerated ID to get the public one I get this:
![image](https://github.com/cloudinary-community/next-cloudinary/assets/95737443/b514d91b-e561-48ab-b91c-fd5ab2671664)

## **Steps To Reproduce the error**

1. create a new video page
2. Query the video as such: 
```
export default function VideoPage({
  params: { id },
}: {
  params: { id: string };
}) {
  const video = useQuery(api.videos.getById, { id: id as Id<"video"> });
  return (
    <div>
    </div>
  );
}

```
3. Import the component and pass the publicId prop:
```
<CldVideoPlayer
        width="720"
        height="1280"
        src={video?.cldPublicId!}
        transformation={{
          streaming_profile: "hd",
        }}
        sourceTypes={["hls"]}
      />

```

## **Expected behaviour**

A thumbnail would show to indicate video is ready

### **Your environment**

- OS: Windows 11 23H2 (22361.3085)
- Node version: 20
- Npm version: pnpm v8.15.0
- Browser name and version: Brave v121

**Comment by colbyfayock** [comment]
hey @monstajoe2002 the code you show looks pretty standard. can you try hardcoding the ID to see if the player works without the dynamic part? do you see any console errors?

**Comment by monstajoe2002** [comment]
Nevermind, I did an early return on the `publicId` and got the video. I also tried hardcoding it and it actually worked. Thanks 👍
