### ISSUE TITLE
CldVideoPlayer Captions

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#430]
### Discussed in https://github.com/cloudinary-community/next-cloudinary/discussions/428

<div type='discussions-op-text'>

<sup>Originally posted by **sunglee** February  8, 2024</sup>
Hi community,

I am new to this library and I am trying to use `CldVideoPlayer` component. In the documentation, it doesn't mention about the video captions/subtitles. Is it possible to configure in `CldVideoPlayer` component?</div>

---

https://cloudinary.com/documentation/video_player_customization#subtitles_and_captions

**Comment by Risini1998** [comment]
I am also trying to add caption for `CldVideoPlayer` component. I couldn't find a way in next-cloudinary documentation. Did I miss anything?
