### ISSUE TITLE
[Bug] Failed to install the package with pnpm

### ISSUE THREAD

**Issue by jercomio** [cloudinary-community/next-cloudinary#446]
# **Failed to install package with pnpm**

Failed to install next-cloudinary package with `pnpm install next-cloudinary`. 

Here is the error in the console :
```
GET https://registry.npmjs.org/next-cloudinary error (ERR_INVALID_THIS)
ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/next-cloudinary: Value of "this" must be of type URLSearchParams

```

<img width="1050" alt="Capture d’écran 2024-03-05 à 11 58 18 AM" src="https://github.com/cloudinary-community/next-cloudinary/assets/99288277/5c8375c4-ad75-45a9-89bf-9cc53aca6bb1">

**Comment by colbyfayock** [comment]
hey, this is a strange one, but i suspect this isn't related to Next Cloudinary

i did a quick search and found this, which may have some info: https://github.com/pnpm/pnpm/issues/6424

the original Bug template for creating this issue included some questions about environment which may speak towards the issue you're having, specifically the node version from some of the comments in that thread

I tested installing it locally on my machine on node 18 and 16
