### ISSUE TITLE
[Bug] quality="auto" or quality="auto:eco" return typescript error

### ISSUE THREAD

**Issue by zecka** [cloudinary-community/next-cloudinary#449]
# **Bug Report**

## **Describe the bug**
Quality in cloudinary seems to allow "auto" or "auto:eco": https://cloudinary.com/blog/the_holy_grail_of_image_optimization_or_balancing_visual_quality_and_file_size#automatic_image_quality_8211_q_auto

If we passe auto to the component we got a typescript errror

![image](https://github.com/cloudinary-community/next-cloudinary/assets/18116930/e6337c07-62ca-4ac6-b994-5ea33ee54114)

## **Is this a regression?**
This is not a regression

### **Your environment**

- Node version: 18.18.2
- Npm version: 9.8.1
- next-coudinary version: 6.1.0

**Comment by colbyfayock** [comment]
thanks for flagging @zecka - just a heads up, the default value for the component is `auto` but `auto:eco` should certainly be supported as well!

**Comment by zecka** [comment]
Thank's @colbyfayock, i updated to 6.1.1 but I stil have the issue

![image](https://github.com/cloudinary-community/next-cloudinary/assets/18116930/0dc4f64b-bf64-4654-a556-204dbae9de65)

I think now it's a conflict with `next/image` props definition
![image](https://github.com/cloudinary-community/next-cloudinary/assets/18116930/9c5fc19b-9d73-4c34-87b1-83d40d567954)

**Comment by colbyfayock** [comment]
ah, i swear i tested it and didnt see any issues, but perhaps i only tested in the core library definition

thanks for the PR, reviewing
