### ISSUE TITLE
getCldVideoUrl don't seem to work on safari

### ISSUE THREAD

**Issue by admin-next-horizon** [cloudinary-community/next-cloudinary#467]
It appears that getCldVideoUrl is not compatible with Safari. The video fails to play, like the player doesn't recognize the format. The example page also does not function properly : https://next.cloudinary.dev/getcldvideourl/examples

**Comment by colbyfayock** [comment]
thanks @admin-next-horizon - the URLs generated were simply using f_auto which can sometimes default to an image format: https://cloudinary.com/documentation/video_optimization#specifying_media_type_with_f_auto

specifying f_auto:video resolves this. a fix is going out shortly for it

**Comment by giopunt** [comment]
Still an issue for me: 

```
const animatedVideoUrl = getCldVideoUrl({
    src: source,
    height: 400,
    format: 'auto:video',
    loop: true,
    crop: 'scale',
});
```
