### ISSUE TITLE
[Bug] chaptersButton not working

### ISSUE THREAD

**Issue by jmsherry** [cloudinary-community/next-cloudinary#469]
# **Bug Report**

## **Describe the bug**

As described [here](https://cloudinary.com/documentation/video_player_customization#video_chapters) in the cloudinary docs and  then used in the `controlBar` prop you should be able to add a button that allows a user to select a chapter, like so:

```jsx
<CldVideoPlayer  controls aiHighlightsGraph showJumpControls playbackRates={[0.25, 0.5, 0.75, 1, 2, 3]} controlBar={{
    chaptersButton: true,
  }} {...props} />
```
**Before going further, I'd like to point out that it doesn't seem to be working on Cloudinary's docs page either!**

## **Is this a regression?**
No.

## **Steps To Reproduce the error**

1. Use the `CldVideoPlayer` component
2. Add the chaptersButton (`controlBar={{ chaptersButton: true, }}`)
3. (Make sure you have chapters added!)
4. Observe how there is no button to allow chapter selection

## **Expected behaviour**

A button appears that allows a user to select a chapter

### **Your environment**

- OS: macOS Sonoma 14.1.1
- Node version:  20.11.1
- Npm version:  10.2.4
- Browser name and version: Chrome Version 123.0.6312.124 (Official Build) (x86_64)

**Comment by colbyfayock** [comment]
hey @jmsherry apologies for the delay

it looks like the parameter was moved out of controlBar into a top level option and the documentation needed to be updated to reflect that, which is now fixed

ive updated the types to also reflect this in the latest version of Next Cloudinary as well as put an example in the documentation

https://next.cloudinary.dev/cldvideoplayer/examples#chapters--selector

**Comment by jmsherry** [comment]
That's awesome! Thank you Colby! :)
