### ISSUE TITLE
Feedback for “CldUploadWidget Examples”

### ISSUE THREAD

**Issue by AbhinasRegmi** [cloudinary-community/next-cloudinary#472]
What is setResouce where does it come from?.

There is no imports given in the example code.

[https://next.cloudinary.dev/clduploadwidget/examples](link)

**Comment by colbyfayock** [comment]
hey @AbhinasRegmi nice catch, setResource in this context is from a useState instance where this is the code I'm using to show the demo example there, but without that context, it's a bit confusing. i'll get this fixed and updated to make it more clear, probably keeping it, but adding useState to show the example of how to make it work

**Comment by colbyfayock** [comment]
pushed an update to include a useState line to hopefully improve clarity

https://next.cloudinary.dev/clduploadwidget/examples
