### ISSUE TITLE
[Feature] Support x & y coordinates on crop

### ISSUE THREAD

**Issue by rafaponieman** [cloudinary-community/next-cloudinary#481]
# **Feature Request**

From all that I have researched, there currently doesn't seem to be a way to support x & y origin coordinates for the crop operation. I tried to work around it but it seems it would involve working on both this library and @cloudinary-util.

In my use case, I have full images that have been cropped by users, giving me x, y, width & height percentages. Working directly with the Cloudinary URLs works fine as long as I specify the percentages as percentage / 100 (x: 50% would be x_0.5). 

Thank you!

**Comment by colbyfayock** [comment]
sorry for the delay here @rafaponieman - should be available on 6.12.0

ex:

```
crop={{
  type: 'crop',
  width: 400,
  height: 400,
  x: 80,
  y: 350,
  gravity: 'north_east',
  source: true
}}
```
