### ISSUE TITLE
VTT error Cannot read properties of undefined (reading 'css')

### ISSUE THREAD

**Issue by nolafs** [cloudinary-community/next-cloudinary#483]
# **Bug Report**

## **Describe the bug**

I am getting an error from VTT in the console using lastest Nextjs 14.

TypeError: Cannot read properties of undefined (reading 'css')
    at e.setupThumbnailElement (index.js:115:40)
    at index.js:107:14

Also it seems it is not able to get the thumbnails from cloudinary.  

https://res.cloudinary.com/ddfaiyncd/video/upload/q_auto/c_fill,g_auto,h_1000,w_1920/fl_sprite/-da66-4772-9985-55184468e94b_ldorqm.vtt

Testing the same link with .webp does return an image. I presume that VTT format is not supported by cloudinary.

## **Steps To Reproduce the error**

Import of the package into my project:

import {CldVideoPlayer} from 'next-cloudinary';
import 'next-cloudinary/dist/cld-video-player.css';

## **Expected behaviour**

No error and thumbnail request only when controls are true

### **Your environment**

- OS: Mac OS
- Node version: 20
- yarn version: 1.22.22
- Browser name and version: all browsers

**Comment by colbyfayock** [comment]
hey @nolafs apologies for never following up on this, are you still experiencing this issue?

I've seen this happen before with configuration issues, can't remember exactly what it was, but wondering if it worked itself out

**Comment by colbyfayock** [comment]
closing since no response, please lmk if you're still experiencing this and reproduction steps
