### ISSUE TITLE
Storing assets on upload with CldUploadWidget

### ISSUE THREAD

**Issue by harryyking** [cloudinary-community/next-cloudinary#488]
When I upload my assets how can i store the image url in my mongodb collection in NextJs

**Comment by colbyfayock** [comment]
the CldUploadWidget component comes with an `onSuccess` prop that allows you to add a callback function upon which the results are passed as an argument that you cab then use to store as you'd like

https://next.cloudinary.dev/clduploadwidget/configuration#callback-functions
https://next.cloudinary.dev/clduploadwidget/examples
