### ISSUE TITLE
[Feature] useId hook for supplying a unique ID for Player instances

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#493]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

We've been struggling to find a good way to provide a unique ID for player instances to avoid conflicts. would this work as a way to ahndle it?

https://react.dev/reference/react/useId

**Comment by sahil9001** [comment]
Can you please assign this to me @colbyfayock ?

**Comment by colbyfayock** [comment]
all yours! let me know if you need any clarifications

**Comment by colbyfayock** [comment]
hey @sahil9001 actually i just realized I had already assigned you an issue. we're limiting active assignments 1 at a time to give people equal opportunity to contribute. once you complete the other one, you can proceed with this one, unless someone else has picked it up first

**Comment by AvaterClasher** [comment]
can i be assigned this @colbyfayock

**Comment by sahil9001** [comment]
> hey @sahil9001 actually i just realized I had already assigned you an issue. we're limiting active assignments 1 at a time to give people equal opportunity to contribute. once you complete the other one, you can proceed with this one, unless someone else has picked it up first

Yeah, I was having tough time figuring that out, so picked this one. I have raised a PR for this, let me know.

**Comment by colbyfayock** [comment]
since you already submitted the PR we can just move forward with it

@AvaterClasher are there any other issues you may be interested in? if not here, there are also some other repos you may be interested in:
- https://github.com/colbyfayock/cloudinary-util
- https://github.com/cloudinary-community/astro-cloudinary
- More: https://cld.media/hacktoberfest
