### ISSUE TITLE
[Bug] Logos aren't showing dark mode version on homepage

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#496]
# **Bug Report**

## **Describe the bug**

We need to show dark mode versions of the images on the homepage

<img width="730" alt="image" src="https://github.com/user-attachments/assets/724b6211-ade3-41ea-bfef-8ff4692bdba0">
<img width="690" alt="image" src="https://github.com/user-attachments/assets/25c79bd5-4c7f-4232-8c04-94bcb663ddb9">

Here are the links to the dark mode images

```
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/v1666934571/images/nextjs-white.svg
https://res.cloudinary.com/colbycloud-next-cloudinary/image/upload/v1666934571/images/cloudinary-white.svg
```

https://github.com/cloudinary-community/next-cloudinary/blob/main/docs/pages/index.mdx?plain=1#L25-L42

im currently solving this with tailwind styles in this example

https://github.com/colbyfayock/astro-cloudinary/pull/2/files#diff-ae669176eb85e8e00b8a6b2541c7d55deba8790db6fba3384459244bc8c8e4f7R18-R60

**Comment by HarshitVashisht11** [comment]
Hi i am interested in fixing this issue
