### ISSUE TITLE
[Feature] ADd documentation for onLoad event for CldImage

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#497]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

https://youtu.be/rW-xDs8HU-o?t=1609

Had trouble finding onLoad in documentation. Should have an events section. This is an inherited Next.js prop

Rather than re-explaining every prop, mention in the events section that the events are inherited and point to the Next.js docs.

**Comment by mr-loop-1** [comment]
Hi @colbyfayock , I would like to add this doc and get familiar with the codebase too. Please assign me.

**Comment by colbyfayock** [comment]
all yours!
