### ISSUE TITLE
[Bug] Video player: "Improper value supplied for aspect ratio. The format should be width:height, for example 16:9. - video.js" when omitting aspectRatio prop

### ISSUE THREAD

**Issue by PhilipAngelinNE** [cloudinary-community/next-cloudinary#499]
# **Bug Report**

## **Describe the bug**

Upgraded from 5.18.0 to >=6.5.0, and the error appears from video.js when using the video player component.

## **Is this a regression?**

Yes, worked previously.

## **Steps To Reproduce the error**

```tsx
<CldVideoPlayer
  config={{ cloud: { cloudName: '...' } }}
  id={id ? id?.concat(uuid) : uuid}
  key={src}
  src={src}
/>
```

However, if I pass an aspect ratio, e.g `aspectRatio="16:9"` the error goes away. But the prop has an optional type (and I see no good reason to enforce aspect ratio?), so something's clearly wrong.

**Comment by colbyfayock** [comment]
Alright I think I found the issue: https://github.com/cloudinary-community/next-cloudinary/pull/461/files

I added the aspectRatio property to the options to help support a fix where the player would jump in sizing when it was loaded, but i hadnt considered the scenario that someone may not be applying a width and a height, which to be honest I didn't remember wasn't required props for the player

That's going to be a fix in Cloudinary Util now as I moved the logic to a helper function to be shared between the different framework libraries, so I'll address it over there and get the fix updated here

In the meantime, do you have a use case where you can't or dont want to use a width and height on the player? Mostly just curious to see how people are using it so i can consider it for future dev

**Comment by colbyfayock** [comment]
hey @PhilipAngelinNE this should be going out in the next release, let me know if this resolves it for you!
