### ISSUE TITLE
CldUploadButton:onUpload={(result: any) => onChange(result.info.secure_url)} Error

### ISSUE THREAD

**Issue by princekumarg** [cloudinary-community/next-cloudinary#508]
it not working in the latest package of "next-cloudinary": "~6.11.0"
<img width="562" alt="image" src="https://github.com/user-attachments/assets/d823e3eb-6cf8-4059-b18e-e341b89836c1">

**Comment by princekumarg** [comment]
can any body help me

**Comment by colbyfayock** [comment]
@princekumarg is it actually not working or are you referring to the line? it's a deprecated method but it should still work as of now

id recommend the `onSuccess` callback instead

**Comment by princekumarg** [comment]
Now it's working on using onSuccess

**Comment by colbyfayock** [comment]
fantastic!
