### ISSUE TITLE
[Feature] Add current version in documentation

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#513]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Add the current version of the SDK in somewhere prominent.

In header? Top of sidebar?

This should be dynamically added based on the package version, not requiring it to be updated manually every time

**Comment by vickywane** [comment]
@colbyfayock I think we can pull this directly from the project `package.json` file to avoid the manual updates. 

Can you please assign this to me?

**Comment by colbyfayock** [comment]
all you @vickywane

**Comment by vickywane** [comment]
Thank you @colbyfayock

**Comment by vickywane** [comment]
@colbyfayock I've opened a PR for this.
