### ISSUE TITLE
[Feature] Caption for CldVideoPlayer component

### ISSUE THREAD

**Issue by Risini1998** [cloudinary-community/next-cloudinary#515]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**
It would be great to have way to add caption/subtitle into `CldVideoPlayer` component.

## **Describe the solution you'd like**
approach like below -> 
`<CldVideoPlayer
  cloudName="your_cloud_name"
  publicId="your_video_public_id"
  textTracks={[
    {
      src: "https://your_domain.com/subtitle.vtt",
      kind: "subtitles",
      label: "English"
    }
  ]}
/>`

**Comment by colbyfayock** [comment]
hey @Risini1998  - available on latest!

https://next.cloudinary.dev/cldvideoplayer/configuration#text-tracks
