### ISSUE TITLE
[Feature] Update CldVideoPlayer Configuration Docs to Table component

### ISSUE THREAD

**Issue by colbyfayock** [cloudinary-community/next-cloudinary#516]
# **Feature Request**

## **Is your feature request related to a problem? Please describe.**

Most of the CldVideoPlayer configuration docs is using the markdown format of defining a table.

<img width="944" alt="image" src="https://github.com/user-attachments/assets/2c4ff260-646f-4484-9563-12413989a33a">

The newer style uses a Table component, looking like this

<img width="871" alt="image" src="https://github.com/user-attachments/assets/03acc25a-0321-40e9-8667-33069ec07ca5">

Migrate all CldVideoPlayer configuration tables in the markdwon format to the Table component. See the Advanced section as an example of the Table component format.

**Comment by Neilblaze** [comment]
@colbyfayock curious, is this up for grabs?

**Comment by colbyfayock** [comment]
Sure, all yours!

**Comment by Neilblaze** [comment]
@colbyfayock, I'm facing some hiccups while running the `/docs` locally. I'm curious, do we need to follow [this](https://github.com/cloudinary-community/next-cloudinary?tab=readme-ov-file#configuration), i.e. we need to ensure that `NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME` is set and configured in our environment **even** for the docs to fire up?

Here's a snap for reference:
![image](https://github.com/user-attachments/assets/22328f52-ce8c-4301-8f1c-88f24708e38e)

> P.S.: I'm currently on **Windows 10 Pro (x64)** & using `pnpm`

**Comment by colbyfayock** [comment]
the Docs uses Next Cloudinary to display all of the examples and the demos and the library requires the Cloud Name to be configured.

theoretically you could add a random value as a cloud name, but the images and videos just won't work on the site. for this particular task, that's not necessarily important, as the Configuration page doesn't include any images or videos

**Comment by Neilblaze** [comment]
The issue which I'm still facing is that, even though I used a dummy string as the `cloud name`, the `pnpm run dev` command is returning the same compile error on my local.

Screenshots:

![image](https://github.com/user-attachments/assets/ae1b71c6-d33f-49b6-86b5-695617ad6df5)

![image](https://github.com/user-attachments/assets/eca94987-e039-4eb8-9060-33c9d2e88644)

Any solution for this?

**Comment by colbyfayock** [comment]
oh that seems like a bit different of an error. can you try running `pnpm run build` in the `next-cloudinary` directory, run `pnpm dev` in the same in a new tab, or you _may_ be able to run `pnpm dev` from the root

i think the library just needs to be built

**Comment by Neilblaze** [comment]
Followed your instructions, here's what I found:

1. The `pnpm run build` in the `next-cloudinary` is working fine and build seems to be successful
![image](https://github.com/user-attachments/assets/ac84918d-77d9-49fe-abfe-08b1fa09b791)

2. But then, when I run `pnpm dev` inside the same directory (after following step-1), it freezes at this —
![image](https://github.com/user-attachments/assets/24da8199-c058-4d69-be05-60f1ee29145f)


3. I tried to execute `pnpn dev` from the root, but it's not working since there's no `dev` script in the [package.json](https://github.com/cloudinary-community/next-cloudinary/blob/main/package.json)

any idea on what I should do next?

**Comment by colbyfayock** [comment]
#2 with `pnpm dev` should be accurate, unless im missing something. its showing the build was successful and now it's waiting for changes. so the idea would be you keep that tab open if any changes are made to the next-cloudinary directory, it will rebuild. if you're not making any changes, just building should suffice, and the docs should then be okay to run

**Comment by Neilblaze** [comment]
@colbyfayock Apologies for the delay, I'll create a PR by today 🙏🏼

**Comment by colbyfayock** [comment]
thanks @Neilblaze - the entire repo is opted into hacktoberfest so should be good :)

**Comment by Neilblaze** [comment]
Sounds good, thanks! 😃
