### ISSUE TITLE
Feedback for “using <CldUploadWidget onUpload={(result,widget)=>{}}></CldUploadWidget>”

### ISSUE THREAD

**Issue by DiasAntony** [cloudinary-community/next-cloudinary#539]
<CldUploadWidget onUpload={(result,widget)=>{
console.log(result)    //can't get result and can't get multiple upload result kindly see and fix!!!
}}></CldUploadWidget>

**Comment by colbyfayock** [comment]
@DiasAntony please use the `onSuccess` callback instead, `onUpload` is deprecated and will be removed in a future release. See: https://next.cloudinary.dev/clduploadwidget/configuration#callback-functions
