### ISSUE TITLE
Feedback for “CldOgImage Examples”

### ISSUE THREAD

**Issue by msafdev** [cloudinary-community/next-cloudinary#547]
U should document how to say:
- apply max width, because the text could overflow behind/above the image if the text is longer
- implement auto-complete on each of the params

**Comment by colbyfayock** [comment]
@msafdev do you mean working with text overlays specifically?

I'm not sure what you mean on the auto-complete perspective, do you mean it's missing some options when you're writing the code? can you let me know what specific ones?

**Comment by colbyfayock** [comment]
Closing until more info is provided
