### ISSUE TITLE
IOS: The Instagram in-app browser failed to load Cloudinary video on the initial render 

### ISSUE THREAD

**Issue by Lanmi2304** [cloudinary-community/next-cloudinary#561]
# **Bug Report**

## **Describe the bug**

I have a video issue in my Next.js project. Specifically, when I navigate to my website from Instagram page, the Cloudinary video fails to load. I've noticed that this problem occurs only on iOS devices. It seems to happen only during the initial render of the home page. However, when I navigate to another page and return to the home page, everything works as expected.

## **Expected behaviour**

Video to be displayed

### **Your environment**

- Node version: v22.11.0
- Npm version:  bun@1.1.33
-  next-cloudinary: "^6.16.0",

 ```
 const url = getCldVideoUrl(
    {
      width: 1920,
      height: 1080,
      src: 'https://res.cloudinary.com/CLOUD_NAME/VIDEO_SRC.mp4',
      quality: 'auto',
    },
    {
      cloud: {
        cloudName: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
        apiKey: process.env.CLOUDINARY_API,
        apiSecret: process.env.CLOUDINARY_API_SECRET,
      },
    },
  );

return   <video
        src={url}
        autoPlay
        loop
        muted
        playsInline
        controls={false}
        className="absolute inset-0 size-full object-cover"
      >
        Your browser does not support the video tag.
      </video>
 ```

**Comment by colbyfayock** [comment]
@Lanmi2304 to be clear are you using getCldVideoUrl here?

**Comment by colbyfayock** [comment]
@Lanmi2304 does this happen repeatedly when using the exact same URL / transformations?

for instance, the same video that you visited once, then perhaps 5 minutes or so later visited again?

reason i ask is the possibility of the video being generated on-the-fly and its just not being available yet, particularly if you're testing amongst different videos with slightly different transformations

is it possible to inspect the request headers at all to see what they look like?

**Comment by Lanmi2304** [comment]
The issue occurs only when I try to open a site using the Instagram app on Apple devices (link in profile description that leads to site URL). On Android, everything works as expected. Additionally, as I mentioned earlier, when I visit the contact page for example  and then return to the home page, the video loads correctly and everything functions properly. The problem arises only during the initial hero render on IOS devices.
